name = Pushtape Divine
description = A layout utilising the golden ratio (or divine proportion).
preview = preview.png
template = pushtape-divine-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/pushtape-divine/pushtape-divine.layout.css
stylesheets[all][] = css/layouts/pushtape-divine/pushtape-divine.layout.no-query.css
