name = Pushtape Simple
description = A simple 1 column layout demonstrating mobile first and Susy.
preview = preview.png
template = pushtape-simple-layout

; Regions
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation bar
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/pushtape-simple/pushtape-simple.layout.css
