<?php
// Plugin definition
$plugin = array(
  'title' => t('Coltrane Double'),
  'icon' => 'coltrane-double.png',
  'category' => t('Pushtape'),
  'theme' => 'coltrane_double',
  'css' => 'css/layouts/coltrane-double/coltrane-double.layout.css',
  'regions' => array(
    'header' => t('Header'),
    'column1' => t('First Column'),
    'column2' => t('Second Column'),
    'middle' => t('Middle'),
    'secondcolumn1' => t('Bottom First Column'),
    'secondcolumn2' => t('Bottom Second Column'),
    'footer' => t('Footer'),
  ),
);

