<?php
// Plugin definition
$plugin = array(
  'title' => t('Santana Flipped'),
  'icon' => 'santana-flipped.png',
  'category' => t('Pushtape'),
  'theme' => 'santana_flipped',
  'css' => 'santana-flipped.css',
  'regions' => array(
    'sidebar' => t('Sidebar'),
    'contentheader' => t('Content Header'),
    'contentcolumn1' => t('Content Column 1'),
    'contentcolumn2' => t('Content Column 2'),
    'contentfooter' => t('Content Footer'),
  ),
);
