name = Bass
description = A single column base layout for pushtape omega.
preview = preview.png
template = bass-layout

; Regions
regions[top]            = Top
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[footer]         = Footer
regions[bottom]         = Bottom


; Stylesheets
;stylesheets[all][] = css/layouts/bass/bass.layout.css
